[package]
authors = ["fpgaminer <fpgaminer@bitcoin-mining.com>"]
description = "Encrypted backup system."
license = "MIT OR Apache-2.0"
name = "preserve"
readme = "README.md"
repository = "https://github.com/fpgaminer/preserve"
version = "0.1.0"

[features]
ceph = ["ceph-rust"]
gluster = ["gfapi-sys"]
vault = ["hashicorp_vault"]

[dependencies]
ceph-rust = {git = "https://github.com/cholcombe973/ceph-rust", optional = true}
clap = "^2.19"
gfapi-sys = {version = "^0.2", optional = true}
libc = "^0.2"
log = "0.3.6"
rand = "^0.3"
rust-crypto = "^0.2"
rust-lzma = "^0.2"
rustc-serialize = "^0.3"
tempdir = "^0.3"
time = "0.1.35"
url = "^1.2"
hashicorp_vault = {version = "^0.6", optional = true}

[dependencies.rust-acd]
git = "https://github.com/fpgaminer/rust-acd.git"
optional = false

[profile.dev]
opt-level = 0      # controls the `--opt-level` the compiler builds with
debug = true       # controls whether the compiler passes `-g`
rpath = false      # controls whether the compiler passes `-C rpath`
lto = false        # controls `-C lto` for binaries and staticlibs
debug-assertions = true # controls whether debug assertions are enabled
codegen-units = 1  # controls whether the compiler passes `-C codegen-units`
                   # `codegen-units` is ignored when `lto = true`
panic = 'unwind'   # panic strategy (`-C panic=...`), can also be 'abort'
